export default {
  tableConfig: [
    {
      leftDisplayName: '企业名称',
      leftFieldName: 'entName',
      rightDisplayName: '机构信用代码',
      rightFieldName: 'creditCode',
    },
    {
      leftDisplayName: '企业信用评分',
      leftFieldName: 'creditScore',
      rightDisplayName: '建议',
      rightFieldName: 'statusName',
    },
    {
      leftDisplayName: '查询日期',
      leftFieldName: 'operateTime',
      rightDisplayName: '查询人',
      rightFieldName: 'operator',
    },
  ],
  basicInfoRows: [
    {
      name1: '企业名称',
      dataIndex1: 'entname',
      name2: '登记机关',
      dataIndex2: 'regorg',
      name3: '经营状态',
      dataIndex3: 'entstatus',
    },
    {
      name1: '注册号',
      dataIndex1: 'regno',
      name2: '许可经营项目',
      dataIndex2: 'abuitem',
      name3: '企业(机构)类型',
      dataIndex3: 'enttype',
    },
    {
      name1: '原注册号',
      dataIndex1: 'oriregno',
      name2: '一般经营项目',
      dataIndex2: 'cbuitem',
      name3: '最后年检日期',
      dataIndex3: 'ancheyear',
    },
    {
      name1: '法定代表人姓名',
      dataIndex1: 'name',
      name2: '经营（业务）范围',
      dataIndex2: '',
      name3: '开业日期',
      dataIndex3: '',
    },
    {
      name1: '注册资本',
      dataIndex1: 'regcap',
      name2: '行业门类代码',
      dataIndex2: 'industryphycode',
      name3: '实收资本(万元)',
      dataIndex3: '',
    },
    {
      name1: '币种',
      dataIndex1: 'regcapcur',
      name2: '注销日期',
      dataIndex2: 'candate',
      name3: '吊销日期',
      dataIndex3: 'revdate',
    },
    {
      name1: '最后年检年度',
      dataIndex1: 'ancheyear',
      name2: '经营期限自',
      dataIndex2: '',
      name3: '国民经济行业名称',
      dataIndex3: 'industryconame',
    },
    {
      name1: '国民经济行业代码',
      dataIndex1: 'industrycocode',
      name2: '变更日期',
      dataIndex2: '',
      name3: '住址',
      dataIndex3: '',
    },
    {
      name1: '注册省份',
      dataIndex1: '',
      name2: '注册部门编码',
      dataIndex2: '',
      name3: '行业门类名称',
      dataIndex3: '',
    },
  ],
  shareholderRows: [
    {
      name1: '股东名称',
      dataIndex1: 'shaname',
      name2: '认缴出资额',
      dataIndex2: 'subconam',
      name3: '认缴出资币种',
      dataIndex3: 'regcapcur',
    },
    {
      name1: '出资比例',
      dataIndex1: 'fundedratio',
      name2: '出资日期',
      dataIndex2: 'condate',
      name3: '国别',
      dataIndex3: 'country',
    },
    {
      name1: '股东总数量',
      dataIndex1: 'invamount',
      name2: '出资额',
      dataIndex2: 'sumconam',
      name3: '股东出资比例总和',
      dataIndex3: 'invsumfundedratio',
    },
  ],
  personRows: [
    {
      name1: '股东名称',
      dataIndex1: 'pername',
      name2: '认缴出资额',
      dataIndex2: 'personamount',
      name3: '认缴出资币种',
      dataIndex3: 'regcapcur',
    },
    {
      name1: '出资比例',
      dataIndex1: 'fundedratio',
      name2: '出资日期',
      dataIndex2: 'condate',
      name3: '国别',
      dataIndex3: 'country',
    },
  ],
  judgmentRows: [
    {
      name1: '姓名',
      dataIndex1: '',
      name2: '身份证号/组织机构代码',
      dataIndex2: '',
      name3: '证件类型',
      dataIndex3: '',
    },
    {
      name1: '数据时间',
      dataIndex1: '',
      name2: '数据类型',
      dataIndex2: '',
      name3: '数据类型编码',
      dataIndex3: '',
    },
    {
      name1: '标题',
      dataIndex1: '',
      name2: '案由',
      dataIndex2: '',
      name3: '当事人住址',
      dataIndex3: '',
    },
    {
      name1: '诉讼地位',
      dataIndex1: '',
      name2: '法定代表人/负责人',
      dataIndex2: '',
      name3: '审理程序',
      dataIndex3: '',
    },
    {
      name1: '审理法院',
      dataIndex1: '',
      name2: '文书字号',
      dataIndex2: '',
      name3: '文书类型',
      dataIndex3: '',
    },
    {
      name1: '审结日期',
      dataIndex1: '',
      name2: '源文件',
      dataIndex2: '',
      name3: 'PDF 文件',
      dataIndex3: '',
    },
    {
      name1: '文书内容',
      dataIndex1: '',
      name2: '异议内容',
      dataIndex2: '',
      name3: '异议时间',
      dataIndex3: '',
    },
  ],
  loseCreditPersonRows: [
    {
      name1: '姓名',
      dataIndex1: '',
      name2: '身份证号/组织机构代码',
      dataIndex2: '',
      name3: '证件类型',
      dataIndex3: '',
    },
    {
      name1: '数据时间',
      dataIndex1: '',
      name2: '数据类型',
      dataIndex2: '',
      name3: '数据类型编码',
      dataIndex3: '',
    },
    {
      name1: '法定代表人/负责人',
      dataIndex1: '',
      name2: '住所地',
      dataIndex2: '',
      name3: '执行法院',
      dataIndex3: '',
    },
    {
      name1: '立案时间',
      dataIndex1: '',
      name2: '执行案号',
      dataIndex2: '',
      name3: '执行标的',
      dataIndex3: '',
    },
    {
      name1: '执行依据文号',
      dataIndex1: '',
      name2: '做出执行依据单位',
      dataIndex2: '',
      name3: '生效法律文书确定的义务',
      dataIndex3: '',
    },
    {
      name1: '生效法律文书确定的最后履行义务截止时间',
      dataIndex1: '',
      name2: '被执行人的履行情况',
      dataIndex2: '',
      name3: '失信被执行人行为具体情形',
      dataIndex3: '',
    },
    {
      name1: '认定失信时间',
      dataIndex1: '',
      name2: '发布时间',
      dataIndex2: '',
      name3: '异议内容',
      dataIndex3: '',
    },
  ],
  limitHighPurchaseRows: [
    {
      name1: '姓名',
      dataIndex1: '',
      name2: '身份证号/组织机构代码',
      dataIndex2: '',
      name3: '证件类型',
      dataIndex3: '',
    },
    {
      name1: '数据时间',
      dataIndex1: '',
      name2: '数据类型',
      dataIndex2: '',
      name3: '数据类型编码',
      dataIndex3: '',
    },
    {
      name1: '法定代表人/负责人',
      dataIndex1: '',
      name2: '住所地',
      dataIndex2: '',
      name3: '执行法院',
      dataIndex3: '',
    },
    {
      name1: '立案时间',
      dataIndex1: '',
      name2: '执行案号',
      dataIndex2: '',
      name3: '执行标的',
      dataIndex3: '',
    },
    {
      name1: '案由',
      dataIndex1: '',
      name2: '发布时间',
      dataIndex2: '',
      name3: '具体内容',
      dataIndex3: '',
    },
    {
      name1: '执行依据',
      dataIndex1: '',
      name2: '异议内容',
      dataIndex2: '',
      name3: '异议时间',
      dataIndex3: '',
    },
  ],
  entRiskSummary: [
    '1.司法案例信息（0条概要信息）',
    '4.司法执行信息（0条概要信息）',
    '7.司法失信信息（0条概要信息）',
    '2.开通公告信息（0条概要信息）',
    '5.审批流程信息（0条概要信息）',
    '8.其他司法公告概要信息（0条概要信息）',
    '3.税务行政执法（0条概要信息）',
    '6.催欠公告（0条概要信息）',
    '9.网贷逾期（0条概要信息）',
  ],
  personRiskSummary: [
    '1.司法案例信息（0条概要信息）',
    '3.司法执行信息（0条概要信息）',
    '5.司法失信信息（0条概要信息）',
    '2.税务行政执法（0条概要信息）',
    '4.催欠公告（0条概要信息）',
    '6.网贷逾期（0条概要信息）',
  ],
};
